"""add_property_types_and_reqs

Revision ID: 1b748f26742e
Revises: 39356262e5bf
Create Date: 2026-09-24 22:50:53.718563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b748f26742e'
down_revision: Union[str, Sequence[str], None] = '39356262e5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('property_type', sa.String(length=50), nullable=True))
    op.add_column('properties', sa.Column('contract_requirements', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'contract_requirements')
    op.drop_column('properties', 'property_type')
    # ### end Alembic commands ###
